model_name: "meta-llama/Llama-3.2-1B"
load_checkpoint_path: "tinker://85dd9574-90a7-5627-9f93-3013ff338113:train:0/weights/final"
learning_rate: 0.00001
dpo_beta: 0.1
lr_schedule: "linear"
num_epochs: 1
batch_size: 256
max_length: 8192
lora_rank: 64
save_every: 300
eval_every: 100
wandb_project: "cse5525_dpo_filtered"
max_steps: null
inline_evals: null
infrequent_eval_every: 100
