# DO NOT USE THIS: RESULTS ARE BAD SINCE IT WASN'T FINETUNED ON FULL DATASET
model_name: "meta-llama/Llama-3.2-1B"
dataset: "tulu3"                
learning_rate: 0.0005
lr_schedule: "linear"
num_epochs: 1
batch_size: 128
max_length: 16384
lora_rank: 64
save_every: 5
eval_every: 5
infrequent_eval_every: 10
wandb_project: "cse5525_sft"
max_steps: 10        # Don't use 
load_checkpoint_path: null
inline_evals: null